### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by zallek** [zallek/swagger-diff#1]
#### break
- [x] Delete path
- [x] Edit OperationId
- [x] Delete OperationId
- [x] Add Param required
- [x] Edit Param required
- [x] Edit Param type
- [x] Edit Param location (in)
- [x] Edit Host
- [x] Edit BasePath
- [x] Edit Array collectionFormat
- [x] Edit Array items type (in param, response, ...)
- [x] Add required object property (need to inline)
- [x] Edit Object Property required (need to inline)
- [x] Edit Object Property type

#### smooth
- [x] Add path
- [x] Add optional param
- [x] Delete a param
- [x] Add optional Object Property
- [x] Delete Object Property

#### todo later
- [ ] Edit Security
- [ ] Edit Produced mime types
- [ ] Edit Consumed mime types
